import type { Metadata } from "next";
import "./globals.css";
import { ReactQueryClientProvider } from "@/services/components/Provider";
import { TitleBar } from "@/components/organisms/TitleBar/TitleBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReactQueryClientProvider>
          <TitleBar />
          {children}
        </ReactQueryClientProvider>
      </body>
    </html>
  );
}
